version: '3'

networks:
  dating-net:
    external:
      name: chat-api-network

services:

  pay-nginx:
    container_name: pay-nginx
    build: docker/nginx
    stdin_open: true
    depends_on:
      - pay-php-fpm
    ports:
      - "1010:1000"
    volumes: # Передает кофигурацию для веб-сервера
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www
    networks:
      - dating-net

  pay-php-fpm:
    container_name: pay-php-fpm
    build: docker/php_fpm
    env_file: .env
    #depends_on:
    #  - db
    environment:
      APP_DEBUG: ${APP_DEBUG}
      DB_HOST: db
      DB_PORT: ${DB_PORT} #Порт подключения к базе данных
      DB_DATABASE: ${DB_DATABASE} #Имя базы данных
      DB_USERNAME: ${DB_USERNAME} #Имя пользователя для подключения к базе данных
      DB_PASSWORD: ${DB_PASSWORD} #Пароль для подключения к базе данных
    stdin_open: true
    volumes:
      - ./src:/var/www
    networks:
      - dating-net


  #db:
  #  image: postgres
  #  container_name: postgresdb_dating
  #  env_file: .env
 #   environment:
 #       - POSTGRES_USER=${DB_USERNAME}
  #      - POSTGRES_PASSWORD=${DB_PASSWORD}
  #      - POSTGRES_DB=${DB_DATABASE}
  #      - PGDATA=/var/lib/postgresql/data/pgdata
 #   ports:
  #      - 5000:5432
 #   volumes:
 #       - pgdata:/var/lib/postgresql/data
 #   healthcheck:
 #       test: [ "CMD-SHELL", "pg_isready -U sa -d ${DB_DATABASE}" ]
 #       interval: 10s
#        timeout: 5s
#        retries: 5
 #   networks:
 #       - dating-net
